version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    port:
      - "9443:9443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker_volumes/portainer_data:/data

volumes:
  portainer_data:
  
